"""
This script is designed to reduce the double support values in a Newick format
tree generated by IQ-TREE and remove the first support value (the single
branch value) leaving only the second support value (bootstrap value)
Created by David E. Hufnagel on May 23, 2020
"""
import sys

inp = open(sys.argv[1])
out = open(sys.argv[2], "w")



firstLine = True
for line in inp:
    newChunks = []
    for chunk in line.split(")"):
        if firstLine:
            newChunks.append(chunk)
            firstLine = False
        else:
            if "/" in chunk:
                newChunk = chunk.split("/")[1]
                newChunks.append(newChunk)
            else:  #for the last line
                newChunks.append(chunk)
    
    newTree = ")".join(newChunks)
    out.write(newTree)
        





inp.close()
out.close()

